package com.p1
{
   import flash.display.Sprite;

   /**
    * @author ACampitelli
    */
   public class P1 extends Sprite
   {
      public function P1()
      {
         //var a:Example1;
         var s:String="qwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbgqwertyuiop;lkjhgfdsazxcvbnm,.oikmnuyhbvredxcfrewdfghyuikmnbgrdcvbnjkikmnbg";
      }
   }
}
